### ISSUE TITLE
Latest blog entry not visible in ATOM/JSON feeds

### ISSUE THREAD

**Issue by sio** [NetOpWibby/blog#5]
[Latest blog post](https://blog.webb.page/2022-06-10-hard-fork-community.txt) is not included into ATOM and JSON feeds.

Is this done intentionally or a bug?

**Comment by NetOpWibby** [comment]
Oh wow, this is super old. My apologies for the lateness. Looks like it was just a bug.

**Comment by NetOpWibby** [comment]
I've decided to move that post and other Handshake drama post to a new top-level folder, "redact." I don't like link rot but I think community issues that are no longer prevalent don't need endless visibility.
